ALTER TABLE sightings ADD COLUMN IF NOT EXISTS rx_lat DOUBLE PRECISION;
ALTER TABLE sightings ADD COLUMN IF NOT EXISTS rx_lon DOUBLE PRECISION;
ALTER TABLE sightings ADD COLUMN IF NOT EXISTS rx_alt DOUBLE PRECISION;
